# Generated by Django 5.2 on 2025-04-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_autor_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
