# Generated by Django 5.2 on 2025-04-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_livros_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='qauntidade',
            new_name='quantidade',
        ),
    ]
