# Generated by Django 5.2.1 on 2025-06-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='Editora',
            new_name='editora',
        ),
    ]
